### PR TITLE
Add debug flag for forcing videoview

### PR DESCRIPTION
**Pull request by johywang**

### CODE REVIEW

**Comment by jblebrun** [comment]
Cool!

**Comment by nbcklim** [comment]
lgtm

**Comment by johywang** [comment]
me tabs are messed up

**Comment by jblebrun** [comment]
wut?

**Comment by jblebrun** [comment]
(I hope this comment trail doesn't end up being discovered as an example of "communication in the 21st century")

**Comment by johywang** [comment]
Oh, I was just commenting that their code uses 4 whitespaces for tabs, but I was using tabs. Sorry my engrish not good.

**Pull request merged**
